# POE Macro v3.0 Default Configuration

# General settings
general:
  debug_mode: false
  log_level: INFO
  language: ja

# Hotkey settings
hotkeys:
  toggle_macro: F1
  emergency_stop: F12
  flask_1: "1"
  flask_2: "2"
  flask_3: "3"
  flask_4: "4"
  flask_5: "5"

# Flask module settings
flask:
  enabled: true
  slot_1:
    enabled: true
    name: "Granite Flask"
    key: "1"
    duration: 7.2
    loop_delay: [7.21, 7.30]
  slot_2:
    enabled: true
    name: "Cinderswallow Urn"
    key: "2"
    duration: 7.2
    loop_delay: [7.21, 7.30]
  slot_4:
    enabled: true
    name: "Wine of the Prophet"
    key: "4"
    duration: 20.0
    loop_delay: [20.0, 21.0]
  slot_5:
    enabled: true
    name: "Divine Mana Flask"
    key: "5"
    duration: 5.0
    loop_delay: [4.5, 4.8]

# Skill module settings
skills:
  enabled: true
  berserk:
    enabled: true
    key: "e"
    interval: [0.3, 1.0]
  molten_shell:
    enabled: true
    key: "r"
    interval: [0.3, 1.0]
  order_to_me:
    enabled: true
    key: "t"
    interval: [3.5, 4.0]

# Screen capture settings
screen_capture:
  monitor_index: 0
  capture_area:
    x: 0
    y: 0
    width: 1920
    height: 1080

# Tincture module settings
tincture:
  enabled: true
  key: "3"
  monitor_config: "Primary"
  sensitivity: 0.7
  check_interval: 0.1  # seconds
  min_use_interval: 0.5  # seconds
  detection_mode: "full_flask_area"  # "manual", "auto_slot3", or "full_flask_area"
  # 手動設定エリア（フラスコエリア全体）
  detection_area:
    x: 914     # 検出エリアのX座標
    y: 1279    # 検出エリアのY座標
    width: 398 # 検出エリアの幅
    height: 160 # 検出エリアの高さ
  # 3番スロット自動計算用の設定（auto_slot3モード時）
  auto_slot3_config:
    x: 1680    # 3番スロットのX座標
    y: 1133    # フラスコエリアのY座標
    width: 80  # Tinctureの幅
    height: 120 # Tinctureの高さ

# Log monitoring settings
log_monitor:
  enabled: false
  log_path: "C:/Program Files (x86)/Steam/steamapps/common/Path of Exile/logs/Client.txt"